config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :breeds
  resources :especies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
end

app/models/especie.rb
class Especie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  before_action :set_breed, only: [:show, :edit, :update, :destroy]

  # GET /breeds
  # GET /breeds.json
  def index
    @breeds = Breed.all
  end

  # GET /breeds/1
  # GET /breeds/1.json
  def show
  end

  # GET /breeds/new
  def new
    @breed = Breed.new
  end

  # GET /breeds/1/edit
  def edit
  end

  # POST /breeds
  # POST /breeds.json
  def create
    @breed = Breed.new(breed_params)

    respond_to do |format|
      if @breed.save
        format.html { redirect_to @breed, notice: 'Breed was successfully created.' }
        format.json { render :show, status: :created, location: @breed }
      else
        format.html { render :new }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breeds/1
  # PATCH/PUT /breeds/1.json
  def update
    respond_to do |format|
      if @breed.update(breed_params)
        format.html { redirect_to @breed, notice: 'Breed was successfully updated.' }
        format.json { render :show, status: :ok, location: @breed }
      else
        format.html { render :edit }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breeds/1
  # DELETE /breeds/1.json
  def destroy
    @breed.destroy
    respond_to do |format|
      format.html { redirect_to breeds_url, notice: 'Breed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breed
      @breed = Breed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def breed_params
      params.require(:breed).permit(:name, :detail)
    end
end

app/controllers/especies_controller.rb
class EspeciesController < ApplicationController
  before_action :set_especy, only: [:show, :edit, :update, :destroy]

  # GET /especies
  # GET /especies.json
  def index
    @especies = Especie.all
  end

  # GET /especies/1
  # GET /especies/1.json
  def show
  end

  # GET /especies/new
  def new
    @especy = Especie.new
  end

  # GET /especies/1/edit
  def edit
  end

  # POST /especies
  # POST /especies.json
  def create
    @especy = Especie.new(especy_params)

    respond_to do |format|
      if @especy.save
        format.html { redirect_to @especy, notice: 'Especie was successfully created.' }
        format.json { render :show, status: :created, location: @especy }
      else
        format.html { render :new }
        format.json { render json: @especy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /especies/1
  # PATCH/PUT /especies/1.json
  def update
    respond_to do |format|
      if @especy.update(especy_params)
        format.html { redirect_to @especy, notice: 'Especie was successfully updated.' }
        format.json { render :show, status: :ok, location: @especy }
      else
        format.html { render :edit }
        format.json { render json: @especy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /especies/1
  # DELETE /especies/1.json
  def destroy
    @especy.destroy
    respond_to do |format|
      format.html { redirect_to especies_url, notice: 'Especie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_especy
      @especy = Especie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def especy_params
      params.require(:especy).permit(:nome_cientifico)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/especies_helper.rb
module EspeciesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/breeds/_form.html.erb
<%= form_with(model: breed, local: true) do |form| %>
  <% if breed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(breed.errors.count, "error") %> prohibited this breed from being saved:</h2>

      <ul>
      <% breed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

<div class="field">
  <%= form.label :detail %>
    <%= form.text_field :detail %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/breeds/edit.html.erb
<h1>Editing Breed</h1>

<%= render 'form', breed: @breed %>

<%= link_to 'Show', @breed %> |
<%= link_to 'Back', breeds_path %>

app/views/breeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Breeds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breeds.each do |breed| %>
      <tr>
        <td><%= breed.name %></td>
        <td><%= link_to 'Show', breed %></td>
        <td><%= link_to 'Edit', edit_breed_path(breed) %></td>
        <td><%= link_to 'Destroy', breed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Breed', new_breed_path %>

app/views/breeds/new.html.erb
<h1>New Breed</h1>

<%= render 'form', breed: @breed %>

<%= link_to 'Back', breeds_path %>

app/views/breeds/show.html.erb
<p id="notice"><%= notice %></p>
<body>

<p id="title"> NEOPET </p>

<p>
  <div class="card text-center">
  <div class="card-header">
</dic>
  <h2><strong><i>Name:</strong></i> <br></h2>
  <h2> <%= @breed.name %> </h2>

</p>
<p>
  <h2><strong> <i>Detail</i>:</strong> <br></h2>
  <h2> <%= @breed.detail %> </h2>
</p>


<p>
<div class="block">
  <p class="frase1"> Este e um paragrafo. </p>
  <p class="frase2"> Este é outro paragrafo. </p>
</div>

</p>
<%= link_to 'Edit', edit_breed_path(@breed), class: 'btn btn-outline-primary' %>

<%= link_to 'Back', breeds_path, class:'btn btn-outline-dark' %>
</body>

app/views/especies/_form.html.erb
<%= form_with(model: especy, local: true) do |form| %>
  <% if especy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(especy.errors.count, "error") %> prohibited this especy from being saved:</h2>

      <ul>
      <% especy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome_cientifico %>
    <%= form.text_field :nome_cientifico %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/especies/edit.html.erb
<h1>Editing Especy</h1>

<%= render 'form', especy: @especy %>

<%= link_to 'Show', @especy %> |
<%= link_to 'Back', especies_path %>

app/views/especies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Especies</h1>

<table>
  <thead>
    <tr>
      <th>Nome cientifico</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @especies.each do |especy| %>
      <tr>
        <td><%= especy.nome_cientifico %></td>
        <td><%= link_to 'Show', especy %></td>
        <td><%= link_to 'Edit', edit_especy_path(especy) %></td>
        <td><%= link_to 'Destroy', especy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Especy', new_especy_path %>

app/views/especies/new.html.erb
<h1>New Especy</h1>

<%= render 'form', especy: @especy %>

<%= link_to 'Back', especies_path %>

app/views/especies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome cientifico:</strong>
  <%= @especy.nome_cientifico %>
</p>

<%= link_to 'Edit', edit_especy_path(@especy) %> |
<%= link_to 'Back', especies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Petshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="nomedaloja">

<h1> NEOPET SHOP </h1>
<img src= "https://3eaf214443cb92a1.cdn.gocache.net/wp-content/uploads/2018/08/brinquedos-para-cachorro-760x450.jpg"/>
</div>